services:
  - type: web
    name: marketing-plan-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: ENVIRONMENT
        value: production
      - key: PORT
        value: 8000
    healthCheckPath: /health